#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Rohan | Unit 5: Interactive Shells

echo "========================================"
echo "   OPEN SOURCE MANIFESTO GENERATOR"
echo "========================================"
echo "Answer three questions to generate your manifesto."
echo ""

# Concept: read for user input
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
USER=$(whoami)
OUTPUT="manifesto_${USER}.txt"

# Concept: Writing to a file with > (overwrite) and >> (append)
echo "--- MY OPEN SOURCE MANIFESTO ---" > $OUTPUT
echo "Generated by: $USER on $DATE" >> $OUTPUT
echo "" >> $OUTPUT

# Concept: String concatenation to form the paragraph
PARA="I believe that the power of technology lies in collaboration. Every day, I rely on $TOOL to navigate the digital world. To me, the essence of open source is $FREEDOM. Because I stand on the shoulders of giants, I commit to the community that I will build $BUILD and share it freely with the world."

echo "$PARA" >> $OUTPUT

echo ""
echo "Success: Manifesto saved to $OUTPUT"
echo "----------------------------------------"
# Concept: Displaying the content of the generated file
cat $OUTPUT

# Note: Demonstrated alias concept via a comment as per requirements
# To run this faster next time, use: alias mygen='./script5.sh'
